
- platform: mqtt
  state_topic: homie/a020a61590a1/pir/motion
  name: kitchen_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a61590a1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  state_topic: homie/a020a6158af1/pir/motion
  name: office_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a6158af1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  state_topic: homie/a020a616efd1/pir/motion
  name: hall_upstairs_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a616efd1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  state_topic: "sonoff3/button/0"
  name: pool_button
  payload_on: "1"
  payload_off: "2"
  availability_topic: "sonoff3/status"
  payload_available: "1"
  payload_not_available: "0"

