
- platform: mqtt
  state_topic: homie/a020a61590a1/pir/motion
  name: kitchen_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a61590a1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  state_topic: homie/a020a6158af1/pir/motion
  name: office_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a6158af1/$online"
  payload_available: "true"
  payload_not_available: "false"

