
- platform: mqtt
  state_topic: homie/5ccf7fd38d01/$online
  name: ir_blaster_heartbeat
  payload_on: "true"
  payload_off: "false"
  device_class: connectivity

- platform: mqtt
  state_topic: homie/a020a61590a1/pir/motion
  name: kitchen_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy

- platform: mqtt
  state_topic: homie/a020a61590a1/$online
  name: kitchen_pir_heartbeat
  payload_on: "true"
  payload_off: "false"
  device_class: connectivity

- platform: mqtt
  state_topic: tele/sonoff1/LWT
  name: sonoff1_heartbeat
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity

- platform: mqtt
  state_topic: tele/sonoff2/LWT
  name: sonoff2_heartbeat
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity

- platform: mqtt
  state_topic: tele/sonoff_t1/LWT
  name: sonoff_t1_heartbeat
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity

- platform: mqtt
  state_topic: tele/sonoff_t2/LWT
  name: sonoff_t2_heartbeat
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity

