
- platform: template
  sensors:
    door_guestroom:
      device_class: motion
      value_template: '{{ states("timer.door_guestroom_open") == "active" }}'
    
    office_screens:
      value_template: '{{ states("sensor.pow1_apparent")|float > 180 }}'

    projector:
      value_template: '{{ states("sensor.pow2_apparent")|float > 200 }}'  # nothing: 47 W, amplifier: 89 W, projector on eco: 134 W, amp + projector: 260 W

