
- platform: template
  sensors:
    door_guestroom:
      device_class: motion
      value_template: '{{ states("timer.door_guestroom_open") == "active" }}'
    
    office_screens:
      value_template: '{{ states("sensor.pow1_apparent")|float > 180 }}'

    projector:
      value_template: '{{ states("sensor.pow2_apparent")|float > 100 }}'  # projector on eco: 134 W

