homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Prague
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

config:

map:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
#logbook:

recorder:
  include:
     entities:
       - binary_sensor.kitchen_pir
       - binary_sensor.office_pir
       - binary_sensor.hall_upstairs_pir
       - sensor.kitchen_luxmeter
       - sensor.office_luxmeter
       - light.office_lamp
       - sensor.hall_upstairs_luxmeter
       - light.kidsroom_bedlight
       - light.kitchen_moodlight
       - light.kitchen_counter
       - light.livingroom_moodlight
       - light.hall_upstairs
       - switch.sonoff_t1
       - switch.sonoff_t2
       - switch.sonoff1
       - switch.sonoff2
       - sensor.living_room_temperature
       - sensor.living_room_pressure
       - sensor.sonoff1_temperature
       - sensor.sonoff1_humidity
#      - input_boolean.bed_time
#      - input_boolean.away_mode
       - media_player.kodi
       - media_player.mpd
       - media_player.projektor_svetice
       - input_number.life_intensity_hr
       - sensor.pool_temperature
       - sensor.solar_collector_temperature
       - switch.pool
       - switch.socket1
       - switch.pow1
       - sensor.pow1_apparent
#      - input_boolean.pool_automation
     domains:
       - input_boolean
#      - sensor
#      - binary_sensor
#      - switch

homekit:
  filter:
    include_entities:
      - switch.sonoff_t1
      - switch.sonoff_t2
      - switch.sonoff1
      - switch.pool
      - light.kitchen_counter
      - light.kitchen_moodlight
      - light.livingroom_moodlight
      - light.kidsroom_bedlight
      - light.hall_upstairs
      - light.office_lamp
      - sensor.pool_temperature
      - sensor.solar_collector_temperature
      - sensor.living_room_temperature
      - sensor.hall_upstairs_luxmeter
      - sensor.kitchen_luxmeter
      - sensor.office_luxmeter

# Text to speech
tts:
  platform: google
  language: cs

media_player:
  - platform: kodi
    host: pi3
    port: 80
  - platform: cast
  - platform: mpd
    host: mpd
  - platform: mpd
    name: office
    host: octoprint

mqtt:
  broker: mqtt

device_tracker:
  - platform: ping
    hosts:
      lenka: lenkahtc
      lenka_air: lenka-air
#  - platform: snmp
#    host: 192.168.1.1
#    comunity: public
#    baseoid: 1.3.6.1.2.1.4.22.1.2
#    new_device_defaults:
#      track_new_devices: False
  - platform: owntracks

# Zones

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    icon: mdi:home
    radius: 50
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    icon: mdi:briefcase
    radius: 250
  - name: School
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    icon: mdi:school
    radius: 80
  - name: Kindergarten
    latitude: !secret kindergarten_latitude
    longitude: !secret kindergarten_longitude
    icon: mdi:baby
    radius: 50

#zeroconf:

#camera: !include_dir_merge_named camera
binary_sensor: !include_dir_merge_list binary_sensor
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
light:  !include_dir_merge_list light
script: !include_dir_merge_named script
group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
scene: !include_dir_merge_list scene
counter: !include_dir_merge_named counter
timer: !include_dir_merge_named timer

#logger:
#  default: warning
#  logs:
#     homeassistant.components.mqtt: debug


