homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Prague
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
#introduction:

default_config:
mobile_app:
ios:

# Enables the frontend
frontend:

config:

map:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
#logbook:

recorder:
  include:
     entities:
       - alarm_control_panel.jablotron
       - binary_sensor.kitchen_pir
       - binary_sensor.socket1_pir
       - binary_sensor.office_pir
       - binary_sensor.hall_upstairs_pir
       - binary_sensor.basement_pir
       - binary_sensor.office_screens
       - binary_sensor.projector
       - binary_sensor.patio_door
       - binary_sensor.bathroom_pir
       - binary_sensor.bathroom_pir_upstairs
       - binary_sensor.bathroom_socket_pir_downstairs
       - binary_sensor.entrance_door
       - binary_sensor.kids_room_door
       - binary_sensor.kids_room_window
       - binary_sensor.bathroom_door_upstairs
       - binary_sensor.bathroom_door_downstairs
       - binary_sensor.bedroom_window
       - binary_sensor.livingroom_pir
       - binary_sensor.office_door
       - binary_sensor.office_window
       - binary_sensor.vestibule_door
       - binary_sensor.vestibule_window
       - binary_sensor.attic_window
       - binary_sensor.basement_door
       - binary_sensor.cloakroom_door
       - binary_sensor.hall_window
       - binary_sensor.bathroom_window_upstairs
       - binary_sensor.bathroom_window_downstairs
       - binary_sensor.livingroom_window
       - sensor.bathroom_luxmeter  
       - sensor.kitchen_luxmeter
       - sensor.office_luxmeter
       - light.office_lamp
       - sensor.hall_upstairs_luxmeter
       - light.kidsroom_bedlight
       - light.kitchen_moodlight
       - light.kitchen_counter
       - light.livingroom_moodlight
       - light.hall_upstairs
       - light.bathroom_light
       - light.bathroom_upstairs
       - switch.office_light
       - switch.kidsroom_light
       - switch.cloakroom_light
       - switch.sonoff1
       - switch.sonoff2
       - switch.sonoff4
       - sensor.living_room_temperature
       - sensor.living_room_pressure
       - sensor.sonoff1_temperature
       - sensor.sonoff1_humidity
       - sensor.sonoff2_temperature
       - sensor.sonoff2_humidity
#      - input_boolean.bed_time
#      - input_boolean.away_mode
       - media_player.kodi
       - media_player.bedplayer
       - media_player.projektor_svetice
       - media_player.office
       - media_player.avr
       - input_number.life_intensity_hr
       - sensor.pool_temperature
       - sensor.solar_collector_temperature
       - switch.pool
       - switch.socket1
       - switch.bathroom_socket
       - switch.bathroom_socket_upstairs
       - switch.bathroom_socket_downstairs
       - switch.pow1
       - switch.water_circulator
#      - sensor.pow1_apparent
#      - input_boolean.pool_automation
       - vacuum.n2d7
     domains:
       - input_boolean
#      - sensor
#      - binary_sensor
#      - switch

homekit:
  filter:
    include_entities:
      - switch.office_light
      - switch.kidsroom_light
      - switch.sonoff1
      - switch.pool
      - light.kitchen_counter
      - light.kitchen_moodlight
      - light.livingroom_moodlight
      - light.kidsroom_bedlight
      - light.hall_upstairs
      - light.office_lamp
      - sensor.pool_temperature
      - sensor.solar_collector_temperature
      - sensor.living_room_temperature
      - sensor.hall_upstairs_luxmeter
      - sensor.kitchen_luxmeter
      - sensor.office_luxmeter

# Text to speech
tts:
  - platform: google_translate
    language: cs

#heos:
#  host: avr

media_player:
#  - platform: kodi
#    host: pi3
#    port: 80
#  - platform: cast
#  - platform: volumio
#    name: bedplayer
#    host: bedplayer
  - platform: mpd
    name: office
    host: octoprint

mqtt:
  broker: mqtt

device_tracker:
  - platform: ping
    hosts:
      lenka: lenkahtc
      lenka_air: lenka-air
#  - platform: snmp
#    host: 192.168.1.1
#    comunity: public
#    baseoid: 1.3.6.1.2.1.4.22.1.2
#    new_device_defaults:
#      track_new_devices: False
#  - platform: owntracks

neato:
  username: !secret neato_username
  password: !secret neato_passwd

# Zones

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    icon: mdi:home
    radius: 50
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    icon: mdi:briefcase
    radius: 250
  - name: School
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    icon: mdi:school
    radius: 80
  - name: Kindergarten
    latitude: !secret kindergarten_latitude
    longitude: !secret kindergarten_longitude
    icon: mdi:baby
    radius: 50

#zeroconf:

#camera: !include_dir_merge_named camera
binary_sensor: !include_dir_merge_list binary_sensor
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
light:  !include_dir_merge_list light
script: !include_dir_merge_named script
group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
scene: !include_dir_merge_list scene
counter: !include_dir_merge_named counter
timer: !include_dir_merge_named timer
alarm_control_panel: !include_dir_merge_list alarm

#logger:
#  default: warning
#  logs:
#     homeassistant.components.mqtt: debug


