- platform: mqtt
  name: "WeMos D1 mini - LED"
  state_topic: "homie/5ccf7fd38d01/led/status"
  command_topic: "homie/5ccf7fd38d01/led/status/set"
  brightness_command_topic: "homie/5ccf7fd38d01/led/brightness/set"
  brightness_state_topic: "homie/5ccf7fd38d01/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/5ccf7fd38d01/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "kitchen_pir_led"
  state_topic: "homie/a020a61590a1/led/status"
  command_topic: "homie/a020a61590a1/led/status/set"
  brightness_command_topic: "homie/a020a61590a1/led/brightness/set"
  brightness_state_topic: "homie/a020a61590a1/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a61590a1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "office_pir_led"
  state_topic: "homie/a020a6158af1/led/status"
  command_topic: "homie/a020a6158af1/led/status/set"
  brightness_command_topic: "homie/a020a6158af1/led/brightness/set"
  brightness_state_topic: "homie/a020a6158af1/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a6158af1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "ibutton_led"
  state_topic: "homie/a020a616f632/led/status"
  command_topic: "homie/a020a616f632/led/status/set"
  brightness_command_topic: "homie/a020a616f632/led/brightness/set"
  brightness_state_topic: "homie/a020a616f632/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a616f632/$online"
  payload_available: "true"
  payload_not_available: "false" 

- platform: mqtt
  name: "hall_upstairs_pir_led"
  state_topic: "homie/a020a616efd1/led/status"
  command_topic: "homie/a020a616efd1/led/status/set"
  brightness_command_topic: "homie/a020a616efd1/led/brightness/set"
  brightness_state_topic: "homie/a020a616efd1/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a616efd1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "office_lamp"
  state_topic: leds7/relay/0
  command_topic: leds7/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: leds7/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: leds7/brightness
  brightness_command_topic: leds7/brightness/set
  rgb_state_topic: leds7/rgb
  rgb_command_topic: leds7/rgb/set
  color_temp_command_topic: leds7/mired/set
  # white_value_state_topic: leds7/channel/3
  # white_value_command_topic: leds7/channel/3/set

