- platform: mqtt
  name: "WeMos D1 mini - LED"
  state_topic: "homie/5ccf7fd38d01/led/status"
  command_topic: "homie/5ccf7fd38d01/led/status/set"
  brightness_command_topic: "homie/5ccf7fd38d01/led/brightness/set"
  brightness_state_topic: "homie/5ccf7fd38d01/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/5ccf7fd38d01/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "kitchen_pir_led"
  state_topic: "homie/a020a61590a1/led/status"
  command_topic: "homie/a020a61590a1/led/status/set"
  brightness_command_topic: "homie/a020a61590a1/led/brightness/set"
  brightness_state_topic: "homie/a020a61590a1/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a61590a1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "office_pir_led"
  state_topic: "homie/a020a6158af1/led/status"
  command_topic: "homie/a020a6158af1/led/status/set"
  brightness_command_topic: "homie/a020a6158af1/led/brightness/set"
  brightness_state_topic: "homie/a020a6158af1/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a6158af1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  name: "ibutton_led"
  state_topic: "homie/a020a616f632/led/status"
  command_topic: "homie/a020a616f632/led/status/set"
  brightness_command_topic: "homie/a020a616f632/led/brightness/set"
  brightness_state_topic: "homie/a020a616f632/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a616f632/$online"
  payload_available: "true"
  payload_not_available: "false" 

- platform: mqtt
  name: "hall_upstairs_pir_led"
  state_topic: "homie/a020a616efd1/led/status"
  command_topic: "homie/a020a616efd1/led/status/set"
  brightness_command_topic: "homie/a020a616efd1/led/brightness/set"
  brightness_state_topic: "homie/a020a616efd1/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "homie/a020a616efd1/$online"
  payload_available: "true"
  payload_not_available: "false"


