- platform: mqtt
  name: "WeMos D1 mini - LED"
  state_topic: "homie/5ccf7fd38d01/led/status"
  command_topic: "homie/5ccf7fd38d01/led/status/set"
  brightness_command_topic: "homie/5ccf7fd38d01/led/brightness/set"
  brightness_state_topic: "homie/5ccf7fd38d01/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "kitchen_pir_led"
  state_topic: "homie/a020a61590a1/led/status"
  command_topic: "homie/a020a61590a1/led/status/set"
  brightness_command_topic: "homie/a020a61590a1/led/brightness/set"
  brightness_state_topic: "homie/a020a61590a1/led/brightness"
  brightness_scale: 1023
  payload_on: "ON"
  payload_off: "OFF"


