binary_sensor:

- platform: mqtt
  state_topic: homie/a020a61590a1/pir/motion
  name: kitchen_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a61590a1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  state_topic: homie/a020a6158af1/pir/motion
  name: office_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a6158af1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  state_topic: homie/a020a616efd1/pir/motion
  name: hall_upstairs_pir
  payload_on: "YES"
  payload_off: "NO"
  device_class: occupancy
  availability_topic: "homie/a020a616efd1/$online"
  payload_available: "true"
  payload_not_available: "false"

- platform: mqtt
  state_topic: "sonoff3/button/0"
  name: pool_button
  payload_on: "1"
  payload_off: "2"
  availability_topic: "sonoff3/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "s20-1/button/0"
  name: socket1_button
  payload_on: "1"
  payload_off: "2"
  availability_topic: "s20-1/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "s20-1/relay/1"
  name: socket1_pir
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy
  availability_topic: "s20-1/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff4/button/1"
  name: basement_pir
  payload_on: "1"
  payload_off: "5"
  device_class: occupancy
  availability_topic: "sonoff4/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff5/relay/1"
  name: bathroom_pir
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy
  availability_topic: "sonoff5/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: bathroom_door_downstairs
  payload_on: "468C0A"
  payload_off: "468C0E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: patio_door
  payload_on: "337A0A"
  payload_off: "337A0E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"
  
- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: kids_room_door
  payload_on: "32E50A"
  payload_off: "32E50E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"
  
- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: kids_room_window
  payload_on: "31520A"
  payload_off: "31520E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"
  
- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: bathroom_door_upstairs
  payload_on: "32F40A"
  payload_off: "32F40E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"
  
- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: entrance_door
  payload_on: "33E00A"
  payload_off: "33E00E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: vestibule_door
  payload_on: "4CB60A"
  payload_off: "4CB60E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: vestibule_window
  payload_on: "4E0E0A"
  payload_off: "4E0E0E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

  
- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: office_door
  payload_on: "322D0A"
  payload_off: "322D0E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: office_window
  payload_on: "47AB0A"
  payload_off: "47AB0E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "livingroom-pir/relay/0"
  name: livingroom_pir
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy
  availability_topic: "livingroom-pir/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: bedroom_window
  payload_on: "4E750A"
  payload_off: "4E750E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: attic_window
  payload_on: "497B0A"
  payload_off: "497B0E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "s20-2/relay/1"
  name: bathroom_pir_upstairs
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy
  availability_topic: "s20-2/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "s20-3/relay/1"
  name: bathroom_socket_pir_downstairs
  payload_on: "1"
  payload_off: "0"
  device_class: occupancy
  availability_topic: "s20-3/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff6/digital"
  name: garden_shed_pir
  payload_on: "0"
  payload_off: "1"
  device_class: occupancy
  availability_topic: "sonoff6/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: livingroom_window
  payload_on: "4AD80A"
  payload_off: "4AD80E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: bathroom_window_downstairs
  payload_on: "4B920A"
  payload_off: "4B920E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: bathroom_window_upstairs
  payload_on: "44A40A"
  payload_off: "44A40E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: hall_window
  payload_on: "48E20A"
  payload_off: "48E20E"
  device_class: "window"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: cloakroom_door
  payload_on: "4A8C0A"
  payload_off: "4A8C0E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

- platform: mqtt
  state_topic: "sonoff-rfbridge/rfin"
  name: basement_door
  payload_on: "41FE0A"
  payload_off: "41FE0E"
  device_class: "door"
  value_template: '{{ value[-6:] }}'
  availability_topic: "sonoff-rfbridge/status"
  payload_available: "1"
  payload_not_available: "0"

