- platform: mqtt
  name: sonoff1
  state_topic: "stat/sonoff1/POWER"
  command_topic: "cmnd/sonoff1/power"
  retain: true
  availability_topic: "tele/sonoff1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: sonoff2
  state_topic: sonoff2/relay/0
  command_topic: sonoff2/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff2/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: sonoff4
  state_topic: sonoff4/relay/0
  command_topic: sonoff4/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff4/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: bathroom_light
  state_topic: sonoff5/relay/0
  command_topic: sonoff5/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff5/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: sonoff_t1
  state_topic: "stat/sonoff_t1/POWER"
  command_topic: "cmnd/sonoff_t1/power"
  retain: true
  availability_topic: "tele/sonoff_t1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: sonoff_t2
  state_topic: "stat/sonoff_t2/POWER"
  command_topic: "cmnd/sonoff_t2/power"
  retain: true
  availability_topic: "tele/sonoff_t2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: pool
  state_topic: sonoff3/relay/0
  command_topic: sonoff3/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff3/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: socket1
  state_topic: s20-1/relay/0
  command_topic: s20-1/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: s20-1/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: pow1
  state_topic: sonoff-pow1/relay/0
  command_topic: sonoff-pow1/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-pow1/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge1
  state_topic: sonoff-rfbridge/relay/0
  command_topic: sonoff-rfbridge/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge2
  state_topic: sonoff-rfbridge/relay/1
  command_topic: sonoff-rfbridge/relay/1/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge3
  state_topic: sonoff-rfbridge/relay/2
  command_topic: sonoff-rfbridge/relay/2/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge4
  state_topic: sonoff-rfbridge/relay/3
  command_topic: sonoff-rfbridge/relay/3/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge5
  state_topic: sonoff-rfbridge/relay/4
  command_topic: sonoff-rfbridge/relay/4/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge6
  state_topic: sonoff-rfbridge/relay/5
  command_topic: sonoff-rfbridge/relay/5/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge7
  state_topic: sonoff-rfbridge/relay/6
  command_topic: sonoff-rfbridge/relay/6/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: rfbridge8
  state_topic: sonoff-rfbridge/relay/7
  command_topic: sonoff-rfbridge/relay/7/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-rfbridge/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: bathroom_socket
  state_topic: s26-1/relay/0
  command_topic: s26-1/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: s26-1/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: pow2
  state_topic: sonoff-pow2/relay/0
  command_topic: sonoff-pow2/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff-pow2/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: water_circulator
  state_topic: sonoff10/relay/0
  command_topic: sonoff10/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: sonoff10/status
  payload_available: 1
  payload_not_available: 0


