- platform: mqtt
  name: sonoff1
  state_topic: "stat/sonoff1/POWER"
  command_topic: "cmnd/sonoff1/power"
  retain: true

- platform: mqtt
  name: sonoff2
  state_topic: "stat/sonoff2/POWER"
  command_topic: "cmnd/sonoff2/power"
  retain: true

- platform: mqtt
  name: sonoff_t1
  state_topic: "stat/sonoff_t1/POWER"
  command_topic: "cmnd/sonoff_t1/power"
  retain: true

- platform: mqtt
  name: sonoff_t2
  state_topic: "stat/sonoff_t2/POWER"
  command_topic: "cmnd/sonoff_t2/power"
  retain: true

