Outside:
  entities:
    - sensor.date
    - sensor.time
    - sun.sun
    - sensor.pws_temp_c
    - sensor.pws_feelslike_c
    - sensor.pws_relative_humidity
    - sensor.pws_wind_kph
    - sensor.pws_wind_gust_kph
    - sensor.pws_pressure_mb

Inside:
  entities:
    - sensor.living_room_temperature
    - sensor.living_room_pressure

