- platform: snmp
  name: router_temperature
  host: router
  baseoid: .1.3.6.1.4.1.14988.1.1.3.10.0
  unit_of_measurement: '째C'
  value_template: "{{((value | int) / 10) | int}}"

- platform: snmp
  name: nas_temperature
  host: alexandria
  baseoid: 1.3.6.1.4.1.6574.1.2.0
  unit_of_measurement: '째C'

- platform: snmp
  name: nas_temperature_disk_1
  host: alexandria
  baseoid: 1.3.6.1.4.1.6574.2.1.1.6.0 
  unit_of_measurement: '째C'

- platform: snmp
  name: nas_temperature_disk_2
  host: alexandria
  baseoid: 1.3.6.1.4.1.6574.2.1.1.6.1
  unit_of_measurement: '째C'

- platform: snmp
  name: petr_bytes_in_total
  host: pracovna.svetice.zahradnikovi.eu
  baseoid: 1.3.6.1.2.1.2.2.1.10.9
  unit_of_measurement: 'bytes'
  scan_interval: 60
  version: '2c'

- platform: snmp
  name: petr_bytes_out_total
  host: pracovna.svetice.zahradnikovi.eu
  baseoid: 1.3.6.1.2.1.2.2.1.16.9
  unit_of_measurement: 'bytes'
  scan_interval: 60
  version: '2c'

- platform: snmp
  name: wan1_bytes_in_total
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.2.2.1.10.14
  unit_of_measurement: 'bytes'
  scan_interval: 1
  version: '2c'

- platform: snmp
  name: wan1_bytes_out_total
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.2.2.1.16.14
  unit_of_measurement: 'bytes'
  scan_interval: 1
  version: '2c'

- platform: snmp
  name: wan2_bytes_in_total
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.2.2.1.10.9
  unit_of_measurement: 'bytes'
  scan_interval: 1
  version: '2c'

- platform: snmp
  name: wan2_bytes_out_total
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.2.2.1.16.9
  unit_of_measurement: 'bytes'
  scan_interval: 1
  version: '2c'

