# Cheap electricity schedule is at:
# https://www.cezdistribuce.cz/edee/content/sysutf/ds3/data/hdo_data.json?&code=197&regionStred=1

- platform: template
  sensors:
    solar_pool_delta:
      friendly_name: "Temperature difference between pool and solar colector"
      entity_id:
        - sensor.pool_temperature
        - sensor.solar_collector_temperature
#     unit_of_measurement: °C
      value_template: "{{ states.sensor.solar_collector_temperature.state|float - states.sensor.pool_temperature.state|float }}"
    rf_code_6:
      friendly_name: "RF code (short)"
      entity_id:
        - sensor.rf_code
      value_template: "{{ states.sensor.rf_code.state[-6:] }}"

    cheap_electricity_left:
      friendly_name: "Cheap electricity left"
      entity_id:
        - sensor.time
      unit_of_measurement: min
      value_template: >-
        0
        {%- if now().weekday() in [5,6] -%}
          {%- set timetable = [
                              {"start": [0, 0], "stop": [0, 10]},
                              {"start": [1, 10], "stop": [8, 35]},
                              {"start": [9, 30], "stop": [11, 55]},
                              {"start": [12, 55], "stop": [20, 10]},
                              {"start": [21, 10], "stop": [23, 59]}
                              ]
          -%}
        {%- else -%}
          {%- set timetable = [
                              {"start": [0, 0], "stop": [7, 15]},
                              {"start": [8, 15], "stop": [9, 55]},
                              {"start": [10, 55], "stop": [12, 30]},
                              {"start": [13, 15], "stop": [17, 30]},
                              {"start": [18, 30], "stop": [23, 59]}
                              ]
          -%}
        {%- endif -%}
        {%- for timedelta in timetable -%}
          {%- set start = timedelta["start"][0]*60 + timedelta["start"][1] -%}
          {%- set stop = timedelta["stop"][0]*60 + timedelta["stop"][1] -%}
          {%- if start > stop -%}
            {%- set stop = stop + 24*60 -%}
          {%- endif -%}
          {%- set cur_time = now().hour*60 + now().minute -%}
          {%- if cur_time > start and cur_time < stop -%}
            {%- set time_left = stop - cur_time -%}
            {{- stop - cur_time -}}
          {%- endif -%}
        {%- endfor -%}
    
