- platform: transmission
  host: !secret transmission_host
  port: !secret transmission_port
  username: !secret transmission_user
  password: !secret transmission_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
