- platform: wunderground
  api_key: !secret wu_api_key
  pws_id: !secret wu_pws_id
  lang: CZ
  monitored_conditions:
    - temp_c
    - relative_humidity
    - pressure_mb
    - weather_1d_metric
    - weather_2d_metric
    - weather_3d_metric
    - weather_1h
    - weather_2h
    - weather_3h
    - temp_high_1d_c
    - temp_low_1d_c
    - temp_high_record_c
    - temp_low_record_c
    - precip_1d_mm
    - precip_1d
    - wind_1d_kph
    - alerts

