
- alias: 'All off when away'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.off_when_away

