
- alias: 'Away: All off when away'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.off_when_away
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id:
          - alarm_control_panel.jablotron

- alias: 'Away: Stuff on when back from away'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'on'
      to: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - group.On_when_away_disabled

- alias: 'Away: nobody home'
  trigger:
    - platform: state
      entity_id: group.people
      from: 'home'
      to: 'not home'
      for:
        minutes: 15
    - platform: state
      entity_id: group.activity_detectors
      from: 'on'
      to: 'off'
      for:
        hours: 12
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id:
          - input_boolean.away_mode


- alias: 'Away: people are home'
  trigger:
    - platform: state
      entity_id: group.people
      from: 'not home'
      to: 'home'
    - platform: state
      entity_id: group.activity_detectors
      from: 'off'
      to: 'on'
      for:
        seconds: 10
    - platform: numeric_state
      entity_id: counter.human_actions_hourly
      above: 5
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id:
          - input_boolean.away_mode

