
- alias: 'Washing machine schedule'
  trigger:
    - platform: state
      entity_id: input_boolean.electricity_is_cheap
      to: 'on'
    - platform: state
      entity_id: input_boolean.washingmachine_scheduled 
      to: 'on'
  condition:
      condition: state
      entity_id: input_boolean.washingmachine_scheduled
      state: 'on'
  action:
    - service_template: >
        {% if float(states("sensor.cheap_electricity_left")) > 80 -%}
        switch.turn_on
        {%- else -%}
        switch.turn_off
        {%- endif %}
      data:
        entity_id:
          - switch.bathroom_socket
    - delay: 00:00:03
    - service_template: >
        {% if float(states("sensor.cheap_electricity_left")) > 80 -%}
        input_boolean.turn_off
        {%- else -%}
        script.dummy
        {%- endif %}
      data:
        entity_id: input_boolean.washingmachine_scheduled

- alias: "LED indication of washing machine schedule"
  trigger:
    - platform: state
      entity_id: input_boolean.washingmachine_scheduled 
  action:
    - service: mqtt.publish
      data_template:
        payload: >-
          {%- if trigger.to_state.state == "on" -%}
          on
          {%- else -%}
          off
          {%- endif -%}
        topic: s26-1/led/0/set

