- alias: 'Bed Time starts at 23:00'
  trigger:
    - platform: time
      after: '23:00:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bed_time


- alias: 'Bed Time ends at 6:00'
  trigger:
    - platform: time
      after: '06:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_time


- alias: 'Night lights'
  trigger:
    - platform: state
      entity_id: input_boolean.bed_time
      to: 'on'
    - platform: state
      entity_id: light.kitchen_counter
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bed_time
        state: 'on'
      - condition: state
        entity_id: light.kitchen_counter
        state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.night_lights


