
- alias: 'Bed Time ends at 6:00'
  trigger:
    - platform: time
      after: '06:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_time


- alias: 'Stuff off after Bed Time'
  trigger:
    - platform: state
      entity_id: input_boolean.bed_time
      from: 'off'
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.sonoff1
          - switch.sonoff2
          - light.kitchen_counter
          - light.kitchen_moodlight
          - light.livingroom_moodlight
      
