
- alias: 'Bed Time ends at 6:55'
  trigger:
    - platform: time
      at: '06:55:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_time


- alias: 'Bed Time: On actions'
  trigger:
    - platform: state
      entity_id: input_boolean.bed_time
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - switch.sonoff1
          - switch.sonoff2
          - light.kitchen_counter
          - light.kitchen_moodlight
          - light.livingroom_moodlight
    - service: input_select.select_option
      data:
          entity_id: input_select.lighting_mode
          option: Night
      
- alias: 'Lighting mode: Night'
  trigger:
    - platform: state
      entity_id: input_boolean.bed_time
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data:
          entity_id: input_select.lighting_mode
          option: Warm
      

