
- alias: 'Bed Time starts when there is dark everywhere and nobody was seen for a while and nobody is watching TV'
  trigger:
    - platform: state
      entity_id: group.activity_detectors
      from: 'on'
      to: 'off'
      for:
        minutes: 45
    - platform: state
      entity_id: binary_sensor.projector
      to: 'off'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.kitchen_luxmeter
        below: 1
      - condition: numeric_state
        entity_id: sensor.office_luxmeter
        below: 1
      - condition: time
        after: '20:00:00'
        before: '04:00:00'
      - condition: state
        entity_id: binary_sensor.projector
        state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bed_time


- alias: 'Bed Time end'
  trigger:
    - platform: time
      at: '06:55:00'
    - platform: state
      entity_id: binary_sensor.entrance_door
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bed_time
        state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_time


- alias: 'Bed Time: On actions'
  trigger:
    - platform: state
      entity_id: input_boolean.bed_time
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - group.off_when_bedtime
    - service: input_select.select_option
      data:
          entity_id: input_select.lighting_mode
          option: Night

      
- alias: 'Bed Time: Off actions'
  trigger:
    - platform: state
      entity_id: input_boolean.bed_time
      from: 'on'
      to: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - group.on_when_bedtime_over

    - service: input_select.select_option
      data:
          entity_id: input_select.lighting_mode
          option: Warm
      

