- alias: 'Cheap electricity on weekdays'
  trigger:
    - platform: time
      at: '8:50:00'
    - platform: time
      at: '11:50:00'
    - platform: time
      at: '15:35:00'
    - platform: time
      at: '20:50:00'
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri 
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.electricity_is_cheap

- alias: 'Expensive electricity on weekdays'
  trigger:
    - platform: time
      at: '7:55:00'
    - platform: time
      at: '10:55:00'
    - platform: time
      at: '14:35:00'
    - platform: time
      at: '19:50:00'
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed 
        - thu
        - fri
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.electricity_is_cheap

- alias: 'Cheap electricity on weekends'
  trigger:
    - platform: time
      at: '8:50:00'
    - platform: time
      at: '11:50:00'
    - platform: time
      at: '15:10:00'
    - platform: time
      at: '20:15:00'
  condition:
    condition: time
    weekday:
        - sat
        - sun
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.electricity_is_cheap

- alias: 'Expensive electricity on weekends'
  trigger:
    - platform: time
      at: '7:55:00'
    - platform: time
      at: '10:55:00'
    - platform: time
      at: '14:10:00'
    - platform: time
      at: '19:15:00'
  condition:
    condition: time
    weekday:
        - sat
        - sun
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.electricity_is_cheap


- alias: 'Cheap electricity notification'
  initial_state: False
  trigger:
    - platform: state
      entity_id: input_boolean.electricity_is_cheap
      to: 'on'
  action:
    - service: script.wall
      data:
        message: 'Právě byla aktivována levnější sazba za elektřinu. Jedna kilowatthodina teď stojí zhruba jednu korunu a dvacet dva haléřů.'


- alias: 'Expensive electricity notification'
  initial_state: False
  trigger:
    - platform: state
      entity_id: input_boolean.electricity_is_cheap
      to: 'off'
  action:
    - service: script.wall
      data:
        message: 'Právě byla aktivována dražší sazba za elektřinu. Jedna kilowatthodina teď stojí zhruba jednu korunu a šedesát haléřů.'


- alias: 'Lighting mode: warm'
  trigger:
    - platform: state
      entity_id: input_boolean.electricity_is_cheap
      from: 'off'
      to: 'on'
  condition:
      condition: state
      entity_id: input_boolean.bed_time
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lighting_mode
        option: Warm

- alias: 'Lighting mode: cold'
  trigger:
    - platform: state
      entity_id: input_boolean.electricity_is_cheap
      from: 'on'
      to: 'off'
  condition:
      condition: state
      entity_id: input_boolean.bed_time
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lighting_mode
        option: Cold


