# Electricity rate schedule
#
# https://www.cezdistribuce.cz/edee/content/sysutf/ds3/data/hdo_data.json?&code=197&regionStred=1
#
# schedule maintained in the template sensor cheap_electricity_left

- alias: 'Cheap electricity off'
  trigger: 
    - platform: numeric_state
      entity_id: sensor.cheap_electricity_left
      below: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.electricity_is_cheap

- alias: 'Cheap electricity on'
  trigger: 
    - platform: numeric_state
      entity_id: sensor.cheap_electricity_left
      above: 0
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.electricity_is_cheap


- alias: 'Lighting mode: warm'
  trigger:
    - platform: state
      entity_id: input_boolean.electricity_is_cheap
      from: 'off'
      to: 'on'
  condition:
      condition: state
      entity_id: input_boolean.bed_time
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lighting_mode
        option: Warm

- alias: 'Lighting mode: cold'
  trigger:
    - platform: state
      entity_id: input_boolean.electricity_is_cheap
      from: 'on'
      to: 'off'
  condition:
      condition: state
      entity_id: input_boolean.bed_time
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.lighting_mode
        option: Cold


