
- alias: 'Circulator timer on'
  trigger:
    - platform: state
      entity_id: timer.water_circulator
      from: "idle"
      to: "active"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.water_circulator

- alias: 'Circulator timer off'
  trigger:
    - platform: state
      entity_id: timer.water_circulator
      from: "active"
      to: "idle"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.water_circulator


- alias: 'Circulator on when motion in bathroom'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.bathroom_door_downstairs
        - binary_sensor.bathroom_door_upstairs
        - binary_sensor.bathroom_pir
      from: "off"
      to: "on"
    - platform: state
      entity_id:
        - binary_sensor.bathroom_door_downstairs
        - binary_sensor.bathroom_door_upstairs
      from: "on"
      to: "off"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.water_circulator
        state: "off"
      - condition: state
        entity_id: input_boolean.away_mode
        state: "off"
  action:
    - service: timer.start
      entity_id: timer.water_circulator


- alias: 'Circulator on with bathroom lights'
  trigger:
    - platform: state
      entity_id:
        - light.bathroom_upstairs
        - switch.bathroom_light
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
  action:
    - service: timer.start
      entity_id: timer.water_circulator


- alias: 'Circulator on when permanent motion in the kitchen'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      from: 'off'
      to: 'on'
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.bed_time
        state: 'off'
  action:
    - service: timer.start
      entity_id: timer.water_circulator


- alias: 'Circulator off when bathroom gets abandoned'
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_pir
      from: "on"
      to: "off"
      for:
        seconds: 30
  condition:
      condition: state
      entity_id: timer.water_circulator
      state: "active"
  action:
    - service: timer.cancel
      entity_id: timer.water_circulator

