- alias: 'House is offline'
  trigger:
    platform: zone
    entity_id: device_tracker.internet
    zone: zone.home
    event: leave
  action:
    - service: script.wall
      data:
        message: 'Tento dům právě přišel o internetovou konektivitu. Pokud je to závada, je třeba jí nahlásit firmě Interconnect na telefonním čísle 2 2 2  2 6 2  3 3 3 .' 

- alias: 'House is online'
  trigger:
    platform: zone
    entity_id: device_tracker.internet
    zone: zone.home
    event: leave
  action:
    - service: script.wall
      data:
        message: 'Internetová konektivita je obnovena'


