
- alias: 'Humidifier on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.sonoff2_humidity
      below: 50 
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'off'
#    - platform: state
#      entity_id: input_boolean.electricity_is_cheap
#      to: 'on'
    - platform: state
      entity_id: switch.sonoff2
      to: 'off'
      for:
        minutes: 15
    - platform: state
      entity_id: binary_sensor.bedroom_window
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.sonoff2_humidity
        below: 60 
      - condition: state
        entity_id: switch.sonoff2
        state: 'off'
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
#      - condition: state
#        entity_id: input_boolean.electricity_is_cheap
#        state: 'on'
      - condition: state
        entity_id: binary_sensor.bedroom_window
        state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonoff2

# Humidifier tank size: 3.5 l
# Evaporation: 0.24 l/h
# Max run time with full tank: 14.4h

- alias: 'Humidifier off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.sonoff2_humidity
      above: 60
#    - platform: state
#      entity_id: input_boolean.electricity_is_cheap
#      from: 'on'
#      to: 'off'
    - platform: state
      entity_id: switch.sonoff2
      to: 'on'
      for: 
        hours: 1
    - platform: state
      entity_id: binary_sensor.bedroom_window
      from: 'off'
      to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.sonoff2
        state: 'on'
#      - condition: numeric_state
#        entity_id: sensor.sonoff2_humidity
#        above: 40
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.sonoff2

