
#
#- alias: 'HDMI to 1 if kodi is playing'
#  trigger:
#    - platform: state
#      entity_id: media_player.kodi
#      to: 'playing'
#  action:
#    - service: script.hdmi_1
#
#
#- alias: 'HDMI to 5 if chromecast is playing'
#  trigger:
#    - platform: state
#      entity_id: media_player.projektor_svetice
#      to: 'playing'
#  action:
#    - service: script.hdmi_5


- alias: "Cinema scene if projector is on"
  trigger:
    - platform: state
      entity_id: binary_sensor.projector
      to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.kitchen_luxmeter
        below: 25
      - condition: state
        entity_id: light.livingroom_moodlight
        state: 'off'
  action:
    - service: script.cinema_scene

- alias: "Lights off if projector and kodi is on"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.projector
        state: 'on'
  action:
    - service: script.black_scene


- alias: "Moodlight off projector is off"
  trigger:
    - platform: state
      entity_id: binary_sensor.projector
      to: "off"
      for:
        minutes: 5
  condition: 
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.kitchen_luxmeter
        below: 25
      - condition: state
        entity_id: light.livingroom_moodlight
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.livingroom_moodlight
        
