
- alias: 'Office light on when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.office_pir
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.office_luxmeter
        below: 0.9
      - condition: state
        entity_id: input_boolean.bed_time 
        state: 'off'
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonoff_t1

- alias: 'Office light off when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.office_pir
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.office_pir
      to: 'off'
      for:
        minutes: 6
    - platform: state
      entity_id: binary_sensor.office_pir
      to: 'off'
      for:
        minutes: 7
  condition:
    condition: state
    entity_id: switch.sonoff_t1
    state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.sonoff_t1


- alias: 'Office PIR Led on when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.office_pir
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_pir_led

- alias: 'Office PIR Led off when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.office_pir
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.office_pir_led


- alias: 'Kitchen PIR Led on when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen_pir_led

- alias: 'Kitchen PIR Led off when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen_pir_led

- alias: 'Hall upstairs PIR Led on when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_upstairs_pir
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hall_upstairs_pir_led

- alias: 'Hall upstairs PIR Led off when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_upstairs_pir
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hall_upstairs_pir_led

- alias: 'Kitchen light on when motion - day'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.kitchen_luxmeter
        below: 15
      - condition: state
        entity_id: light.kitchen_counter
        state: 'off'
      - condition: state
        entity_id: input_boolean.bed_time 
        state: 'off'
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
  action:
    - service: light.turn_on
      data:
        rgb_color: [255, 122, 10]
        entity_id:
          - light.kitchen_counter
          - light.kitchen_moodlight
    # do it twice to work arround a bug in the driver
    - service: light.turn_on
      data:
        rgb_color: [255, 122, 10]
        entity_id:
          - light.kitchen_counter
          - light.kitchen_moodlight


- alias: 'Kitchen light on when motion - night'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.kitchen_luxmeter
        below: 15
      - condition: state
        entity_id: light.kitchen_counter
        state: 'off'
      - condition: state
        entity_id: input_boolean.bed_time 
        state: 'on'
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
  action:
    - service: light.turn_on
      data:
        rgb_color: [5, 0, 0]
        entity_id:
          - light.kitchen_counter
          - light.kitchen_moodlight
          - light.livingroom_moodlight
    # do it twice to work arround a bug in the driver
    - service: light.turn_on
      data:
        rgb_color: [5, 0, 0]
        entity_id:
          - light.kitchen_counter
          - light.kitchen_moodlight
          - light.livingroom_moodlight


- alias: 'Kitchen light off when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'off'
      for:
        minutes: 6
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'off'
      for:
        minutes: 7
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.kitchen_counter
        state: 'on'
      - condition: state
        entity_id: light.kitchen_moodlight
        state: 'on'
      - condition: state
        entity_id: light.livingroom_moodlight
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen_counter
          - light.kitchen_moodlight
          - light.livingroom_moodlight

- alias: 'Kitchen light off when too much light'
  trigger:
    - platform: numeric_state
      entity_id: sensor.kitchen_luxmeter
      above: 200
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.kitchen_luxmeter
      above: 200
      for:
        minutes: 6
    - platform: numeric_state
      entity_id: sensor.kitchen_luxmeter
      above: 200
      for:
        minutes: 7
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.kitchen_counter
        state: 'on'
      - condition: state
        entity_id: light.kitchen_moodlight
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen_counter
          - light.kitchen_moodlight



- alias: 'Hall upstairs light off when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_upstairs_pir
      to: 'off'
      for:
        seconds: 30
    - platform: state
      entity_id: binary_sensor.hall_upstairs_pir
      to: 'off'
      for:
        seconds: 60
    - platform: state
      entity_id: binary_sensor.hall_upstairs_pir
      to: 'off'
      for:
        seconds: 90
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.hall_upstairs
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hall_upstairs
    - service: switch.turn_off
      data:
        entity_id:
          - switch.hall_fluxer

- alias: 'Hall upstairs light on when motion - day'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_upstairs_pir
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.hall_upstairs_luxmeter
        below: 15
      - condition: state
        entity_id: light.hall_upstairs
        state: 'off'
      #- condition: state
      #  entity_id: input_boolean.bed_time 
      #  state: 'off'
      - condition: time
        after: '07:00:00'
        before: '20:00:00'
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.hall_fluxer
    - service: light.turn_on
      data:
        entity_id:
          - light.hall_upstairs
    - service: switch.hall_fluxer_update

- alias: 'Hall upstairs light on when motion - night'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_upstairs_pir
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.hall_upstairs_luxmeter
        below: 15
      - condition: state
        entity_id: light.hall_upstairs
        state: 'off'
      #- condition: state
      #  entity_id: input_boolean.bed_time 
      #  state: 'off'
      - condition: time
        after: '20:00:00'
        before: '07:00:00'
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
  action:
    - service: light.turn_on
      data:
        rgb_color: [5, 0, 0]
        entity_id:
          - light.hall_upstairs
    # do it twice to work arround a bug in the driver
    - service: light.turn_on
      data:
        rgb_color: [5, 0, 0]
        entity_id:
          - light.hall_upstairs
