- alias: 'Kitchen counter on when motion'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'off'
    state: 'on' 
  condition:
      condition: numeric_state 
      entity_id: sensor.kitchen_luxmeter 
      below: '15'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_counter

- alias: 'Kitchen counter off when no motion'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_pir
    state: 'off'
    for: '00:01:00'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_counter


- alias: 'Kitchen moodlight on when motion'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'off'
    state: 'on'
  condition:
    condition: state
    entity_id: input_boolean.bed_time
    state: 'on'
  action:
    - service: script.transition_to_dark_red

- alias: 'Kitchen moodlight off when no motion'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_pir
    state: 'off'
    for: '00:01:05'
  condition:
    condition: state
    entity_id: input_boolean.bed_time
    state: 'on'
  action:
    - service: script.transition_to_black



- alias: 'Livingroom lights on when motion'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_pir
    from: 'off'
    state: 'on'
  condition:
    condition: state
    entity_id: input_boolean.bed_time
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.livingroom
        rgb_color: [5,0,0]

- alias: 'Livingroom lights off when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      state: 'off'
      for: '00:01:10'
    - platform: state
      entity_id: input_boolean.bed_time
      from: 'off'
      state: 'on'
  condition:
    condition: state
    entity_id: input_boolean.bed_time
    state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.livingroom
