- alias: 'PeZ arrived to the Office'
  trigger:
    platform: zone
    entity_id: device_tracker.pez_workphone
    zone: zone.work
    event: enter
  action:
    - service: script.wall
      data:
        message: 'Hlášení o poloze. Petr právě dorazil do kanceláře.'

- alias: 'PeZ left the Office'
  trigger:
    platform: zone
    entity_id: device_tracker.pez_workphone
    zone: zone.work
    event: leave
  action:
    - service: script.wall
      data:
        message: 'Hlášení o poloze. Petr právě odjel ze své kanceláře.'

- alias: 'PeZ arrived to the School'
  trigger:
    platform: zone
    entity_id: device_tracker.pez_workphone
    zone: zone.school
    event: enter
  action:
    - service: script.wall
      data:
        message: 'Hlášení o poloze. Petr právě dorazil do školy.'

- alias: 'PeZ left the School'
  trigger:
    platform: zone
    entity_id: device_tracker.pez_workphone
    zone: zone.school
    event: leave
  action:
    - service: script.wall
      data:
        message: 'Hlášení o poloze. Petr právě opustil školu.'

