
- alias: 'Pool pump on when solar collector hot'
  trigger:
    - platform: numeric_state
      entity_id: sensor.solar_collector_temperature
      above: 30
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.pool_temperature
        below: 30
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.pool

- alias: 'Pool pump off when solar collector cold'
  trigger:
    - platform: numeric_state
      entity_id: sensor.solar_collector_temperature
      below: 27 
    - platform: numeric_state
      entity_id: sensor.pool_temperature
      above: 30
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.pool

