
- alias: 'Group office light switches'
  trigger:
    - platform: state
      entity_id: 
        - switch.rfbridge1
        - switch.sonoff_t1
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge1 
        - switch.sonoff_t1

- alias: 'Group living room lamp switches'
  trigger:
    - platform: state
      entity_id: 
        - switch.rfbridge4
        - switch.sonoff1
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge4 
        - switch.sonoff1

