
- alias: 'Group office light switches'
  trigger:
    - platform: state
      entity_id: 
        - switch.rfbridge1
        - switch.office_light
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge1 
        - switch.office_light

- alias: 'Group office lamp switches'
  trigger:
    - platform: state
      entity_id:
        - switch.rfbridge8
        - light.office_lamp
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge8
        - light.office_lamp

- alias: 'Group living room lamp switches'
  trigger:
    - platform: state
      entity_id: 
        - switch.rfbridge4
        - switch.sonoff1
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% else %}
        script.dummy
        {% endif %}
      entity_id:
        - switch.rfbridge4 
        - switch.sonoff1

- alias: 'Group kids room bed light switches'
  trigger:
    - platform: state
      entity_id:
        - switch.rfbridge3
        - switch.rfbridge6
        - light.kidsroom_bedlight
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge3
        - switch.rfbridge6
        - light.kidsroom_bedlight

- alias: 'Guest Room Door Opened'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:] == "68C4A1" %}
        timer.start
        {% else %}
        script.dummy
        {% endif %}
      entity_id:
        - timer.door_guestroom_open


- alias: 'Viteks controller - random colors on all lights'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service_template: >-
        {%- if trigger.to_state.state[-6:] == "8E3FE4" -%}
        script.dummy
        {%- elif trigger.to_state.state[-6:-1] == "8E3FE" -%}
        light.turn_on
        {%- else -%}
        script.dummy
        {%- endif -%}
      data_template:
        rgb_color: ['{{ "{0:d}".format(range(0,255)|random) }}',
                    '{{ "{0:d}".format(range(0,255)|random) }}',
                    '{{ "{0:d}".format(range(0,255)|random) }}']
        brightness: 255
        entity_id:
          - light.office_lamp
          - light.hall_upstairs
          - light.kitchen_counter
          - light.kitchen_moodlight
          - light.livingroom_moodlight
          - light.kidsroom_bedlight

- alias: 'Andrejka controller - random color on bed light'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:] == "2E54B3" %}
        light.turn_on
        {% else %}
        script.dummy
        {% endif %}
      data_template:
        rgb_color: ['{{ "{0:d}".format(range(0,128)|random) }}',
                    '{{ "{0:d}".format(range(0,128)|random) }}',
                    '{{ "{0:d}".format(range(0,128)|random) }}']
        entity_id:
          - light.kidsroom_bedlight


#
# Playlists
#
# kidsroom_1 - andrejciny/petovo pisnicky
# kidsroom_2 - pohadkove pisnicky
# kidsroom_3 - uhlir
# kidsroom_4 - Soundtracky
# kidsroom_5 - Elder scrolls
# kidsroom_6 - Country
# kidsroom_7 - Dance
# kidsroom_8 - Radio
# kidsroom_9 - Vanocni

- alias: 'Kidsroom player - play/next playlist/prev playlist'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.bedplayer
        state: 'off'
      - condition: state
        entity_id: media_player.bedplayer
        state: 'paused'
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:] == "374271" %}
        media_player.play_media
        {% elif trigger.to_state.state[-6:] == "374272" %}
        media_player.play_media
        {% elif trigger.to_state.state[-6:] == "374274" %}
        media_player.play_media
        {% else %}
        script.dummy
        {% endif %}
      data_template:
        media_content_id: '{{ "kidsroom_{0:d}".format(range(1,9)|random) }}'
        media_content_type: 'playlist'
        entity_id:
          - media_player.bedplayer


- alias: 'Kidsroom player - stop/next/prev'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
      - condition: state
        entity_id: media_player.bedplayer
        state: 'playing'
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:] == "374271" %}
        media_player.media_stop
        {% elif trigger.to_state.state[-6:] == "374272" %}
        media_player.media_previous_track
        {% elif trigger.to_state.state[-6:] == "374274" %}
        media_player.media_next_track
        {% else %}
        script.dummy
        {% endif %}
      data:
        entity_id:
          - media_player.bedplayer


- alias: 'Kidsroom player - presets'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:-1] == "0CD67" %}
        media_player.play_media
        {% else %}
        script.dummy
        {% endif %}
      data_template:
        media_content_id: >
          {% if trigger.to_state.state[-6:] == "0CD671" %}
          kidsroom_8
          {% elif trigger.to_state.state[-6:] == "0CD672" %}
          countryradio
          {% elif trigger.to_state.state[-6:] == "0CD674" %}
          pohadky
          {% elif trigger.to_state.state[-6:] == "0CD678" %}
          povesti
          {% endif %}
        media_content_type: 'playlist'
        entity_id:
          - media_player.bedplayer
      

- alias: 'Toggle things by RF code'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service: homeassistant.toggle
      data_template:
        entity_id: >
          {% if trigger.to_state.state[-6:] == "DAF2E8" %}
            light.livingroom_moodlight
          {% elif trigger.to_state.state[-6:] == "DAF2E2" %}
            switch.sonoff1
          {% elif trigger.to_state.state[-6:] == "DAF2E4" %}
            group.kitchen_lights
          {% elif trigger.to_state.state[-6:] == "DAF2E6" %}
            switch.socket1
          {% elif trigger.to_state.state[-6:] == "DAF2EA" %}
            switch.sonoff2
          {% elif trigger.to_state.state[-6:] == "0623B1" %}
            input_boolean.washingmachine_scheduled
          {% else %}
            script.dummy
          {% endif %}


- alias: 'Turn things on by RF code'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if trigger.to_state.state[-6:] == "DAF2EC" %}
            script.cinema_scene
          {% elif trigger.to_state.state[-6:] == "DAF2EE" %}
            script.black_scene
          {% elif trigger.to_state.state[-6:] == "029C74" %}
            input_boolean.away_mode
          {% elif trigger.to_state.state[-6:] == "2AF3E1" %}
            input_boolean.bed_time
          {% else %}
            script.dummy
          {% endif %}



- alias: 'RF controller identification ON - Peta'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.rf_code_6
        state: '5B33A2'
      - condition: state
        entity_id: group.rgb_lights
        state: 'off'
  action:
    - service: light.turn_on
      data:
        rgb_color: [0, 255, 0]
        brightness: 255
        entity_id: 
          - group.rgb_lights

- alias: 'RF controller identification OFF - Peta'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.rf_code_6
        state: '5B33A2'
      - condition: state
        entity_id: group.rgb_lights
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: 
          - group.rgb_lights

- alias: 'RF controller Peta - bed light red'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.rf_code_6
        state: '5B33A8'
  action:
    - service: light.turn_on
      data:
        rgb_color: [255, 0, 0]
        brightness: 13
        entity_id: 
          - light.kidsroom_bedlight


- alias: 'RF controller identification ON - Vitek'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.rf_code_6
        state: '8E3FE4'
      - condition: state
        entity_id: group.rgb_lights
        state: 'off'
  action:
    - service: light.turn_on
      data:
        rgb_color: [255, 55, 0]
        brightness: 255
        entity_id:
          - group.rgb_lights


- alias: 'RF controller identification OFF - Vitek'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.rf_code_6
        state: '8E3FE4'
      - condition: state
        entity_id: group.rgb_lights
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - group.rgb_lights


- alias: 'RF controller identification ON - Andrejka'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.rf_code_6
        state: '5D91A2'
      - condition: state
        entity_id: group.rgb_lights
        state: 'off'
  action:
    - service: light.turn_on
      data:
        rgb_color: [120, 0, 255]
        brightness: 255
        entity_id:
          - group.rgb_lights

- alias: 'RF controller identification OFF - Andrejka'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.rf_code_6
        state: '5D91A2'
      - condition: state
        entity_id: group.rgb_lights
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - group.rgb_lights


