
- alias: 'Group office light switches'
  trigger:
    - platform: state
      entity_id: 
        - switch.rfbridge1
        - switch.sonoff_t1
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge1 
        - switch.sonoff_t1

- alias: 'Group living room lamp switches'
  trigger:
    - platform: state
      entity_id: 
        - switch.rfbridge4
        - switch.sonoff1
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge4 
        - switch.sonoff1

- alias: 'Group kids room bed light switches'
  trigger:
    - platform: state
      entity_id:
        - switch.rfbridge3
        - switch.rfbridge6
        - light.kidsroom_bedlight
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
        {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge3
        - switch.rfbridge6
        - light.kidsroom_bedlight

- alias: 'Group kids room light switches'
  trigger:
    - platform: state
      entity_id:
        - switch.rfbridge2
        - switch.rfbridge7
        - switch.sonoff_t2
  action:
    - service_template: >
        {% if trigger.to_state.state == "on" %}
        switch.turn_on
        {% elif trigger.to_state.state == "off" %}
        switch.turn_off
        {% endif %}
      entity_id:
        - switch.rfbridge2
        - switch.rfbridge7
        - switch.sonoff_t2

- alias: 'Guest Room Door Opened'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:] == "68C4A1" %}
        timer.start
        {% endif %}
      entity_id:
        - timer.door_guestroom_open


- alias: 'Viteks controller - random colors on all lights'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:-1] == "8E3FE" %}
        light.turn_on
        {% endif %}
      data_template:
        rgb_color: ['{{ "{0:d}".format(range(0,255)|random) }}',
                    '{{ "{0:d}".format(range(0,255)|random) }}',
                    '{{ "{0:d}".format(range(0,255)|random) }}']
        entity_id:
          - light.office_lamp
          - light.hall_upstairs
          - light.kitchen_counter
          - light.kitchen_moodlight
          - light.livingroom_moodlight
          - light.kidsroom_bedlight

- alias: 'Andrejka controller - random color on bed light'
  trigger:
    - platform: state
      entity_id: sensor.rf_code
  action:
    - service_template: >
        {% if trigger.to_state.state[-6:] == "2E54B3" %}
        light.turn_on
        {% endif %}
      data_template:
        rgb_color: ['{{ "{0:d}".format(range(0,128)|random) }}',
                    '{{ "{0:d}".format(range(0,128)|random) }}',
                    '{{ "{0:d}".format(range(0,128)|random) }}']
        entity_id:
          - light.kidsroom_bedlight

