- alias: 'Sunrise notification'
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:01:00"
  action:
    - service: script.wall
      data:
        message: 'in 1 minute there is going to be sunrise. Enjoy the aurora.'

- alias: 'Sunset notification'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
    - service: script.wall
      data:
        message: 'in 5 minutes there is going to be sunset. Enjoy the aurora.'

