- alias: 'Sunrise notification'
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:01:00"
  action:
    - service: script.wall
      data:
        message: 'Za jednu minutu nastane východ slunce. A možná, že budou i červánky.'

- alias: 'Sunset notification'
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
    - service: script.wall
      data:
        message: 'Za 5 minut zapadne slunce. Nejvyšší čas udělat nějaké fotky s pěkným světlem'

