- alias: 'Wakeup song'
  initial_state: False
  trigger:
    - platform: time
      after: '6:42'
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri 
  action:
    - service: script.wakeup

